baseURL = "https://blog.zenosmosis.com"
languageCode = "en-us"
title = "zenOSmosis blog"
# No external theme used; site uses simple internal layouts in /layouts

[outputs]
home = ["HTML", "JSON", "ActivityRSS", "ActivityAtom", "ActivityJSON"]
section = ["HTML", "JSON"]

[mediaTypes]
	[mediaTypes."application/atom+xml"]
		suffixes = ["atom"]

	[mediaTypes."application/feed+json"]
		suffixes = ["json"]

[outputFormats]
	[outputFormats.ActivityRSS]
		name = "ActivityRSS"
		mediaType = "application/rss+xml"
		baseName = "activity"
		suffix = "xml"
		rel = "alternate"
			isPlainText = true

	[outputFormats.ActivityAtom]
		name = "ActivityAtom"
		mediaType = "application/atom+xml"
		baseName = "activity"
		suffix = "atom"
		rel = "alternate"
			isPlainText = true

	[outputFormats.ActivityJSON]
		name = "ActivityJSON"
		mediaType = "application/feed+json"
		baseName = "activity"
		suffix = "json"
		rel = "alternate"
			isPlainText = true

[markup]
	[markup.tableOfContents]
	startLevel = 2
	endLevel = 4
	ordered = false

[params]
author = "jzombie"
description = "Quietly ambitious software, in public."
socialImage = "/social/zenOSmosis-blog-card-1200x630.jpg"
socialImageAlt = "zenOSmosis blog"
